version: "3"
services:
  postgres:
    image: theshultz/kaplat-books-postgres-instance:latest
    ports:
      - "5432:5432"  # Exposing PostgreSQL to the host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: books

  mongo:
    image: theshultz/kaplat-books-mongo-instance:latest
    ports:
      - "27017:27017"  # Exposing MongoDB to the host

  app:
    image: michalmos/book-store:latest
    restart: on-failure
    ports:
      - "4785:8574"  # Map internal app port to the external one
    depends_on:
      - postgres
      - mongo
    environment:
      POSTGRES_HOST: postgres  # Connecting to PostgreSQL service by name
      POSTGRES_PORT: 5432
      MONGO_HOST: mongo  # Connecting to MongoDB service by name
      MONGO_PORT: 27017
